#################################################
# APPLICATION
#################################################
spring.application.name=school-management

#################################################
# SERVER
#################################################
server.port=${PORT:8080}

#################################################
# DATABASE (PostgreSQL)
#################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db
spring.datasource.username=postgres
spring.datasource.password=Ramanujan@1729
spring.datasource.driver-class-name=org.postgresql.Driver

#################################################
# JPA / HIBERNATE
#################################################
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#################################################
# JWT
#################################################
jwt.secret=AnkitSchoolManagementSystemJwtSecretKey2026Secure123456789

#################################################
# LOGGING
#################################################
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#################################################
# JACKSON
#################################################
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=Asia/Kolkata